### ISSUE TITLE
PHP-FPM detection in Docker image

### ISSUE THREAD

**Issue by Codelica** [pydio/cells#2]
Hello...

Trying to install from the Docker image, it appears PHP-FPM is not getting detected properly, yet it is installed:

![mariadb phpmyadmin 4 8 0 1 2018-05-21 17-09-25](https://user-images.githubusercontent.com/386101/40334239-e7972f28-5d19-11e8-806d-20c79d767743.png)

Container created with:

```
docker run -it -d -t \
  --name Cells  \
  --net DockerLocal \
  -v /storage/docker/cells:/home/cells/.config/pydio/cells/ \
  -e "CELLS_BIND=192.168.2.2:8080" \
  -e "CELLS_EXTERNAL=192.168.2.2:8080" \
  -p 8080:8080 \
  pydio/cells
```

DockerLocal is just a local network I have w/ MariaDB and some other private services.

**Comment by cdujeu** [comment]
Hi @Codelica , thanks for reporting. 
Have to recheck that, either the "+" is breaking the version number parsing, or it's more deep and the fpm does not "see" the temporary files we are creating to execute phpinfo() and detect the version.

**Comment by Codelica** [comment]
Gotcha...  let me know if you want me to check anything in the container.

**Comment by laszlo462** [comment]
Any updates on this?  Although the issue I've run into is slightly different, as the php detection is looking at localhost, while the php frontend is a separate container.

**Comment by ghecquet** [comment]
This is fixed in the latest version of the pydio/cells container.

**Comment by stardebris** [comment]
This issue isn't fixed, still occurs with the latest docker image.
